apiVersion: v1
kind: Service
metadata:
  name: health-app-service
  labels:
    app: health-app
spec:
  type: NodePort
  selector:
    app: health-app
    slot: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30080
